### ISSUE TITLE
Having trouble creating a PDF export config

### ISSUE THREAD

**Issue by JoeErani** [Pierre-Sassoulas/django-survey#54]
I am trying to have it setup so that open response questions are formatted as raw and anything else would be a pie chart. Any help would be greatly appreciated

**Comment by Pierre-Sassoulas** [comment]
Hello,

Thank you for your question.

You can use the generic part in order to have a "default" output (for example pie chart), then change the type for other questions (you might need to list all the question, so choose the type with the smaller number of occurrence). For example here you would have a pie chart by default and then raw for the question `Lorem ?` and `Dolor ?` :

```
generic:
      chart:
        type: pie

'Your Survey Name':
  questions:
    'Lorem ?':
      chart:
        type: raw
    'Dolor ?':
      chart:
        type: raw
```

I did not test the YAML file so it might now work as-is. If I remember correctly you can generate the configuration file with `generatetexconf`` (`python manage.py generatetexconf -h` will print the help of the command). It's probably easier to generate everything then remove the question that are treated with the default behaviour.

Let me know if it helps, and do not hesitate to provide your configuration file.
